#!/bin/bash
#
# Copyright (c) 2012, Oracle and/or its affiliates. All rights reserved.
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#
# This code is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 only, as
# published by the Free Software Foundation.
#
# This code is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# version 2 for more details (a copy is included in the LICENSE file that
# accompanied this code).
#
# You should have received a copy of the GNU General Public License version
# 2 along with this work; if not, write to the Free Software Foundation,
# Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
# or visit www.oracle.com if you need additional information or have any
# questions.
#

if [ "$#" != 3 ]; then
    echo usage: getdifferences main-shuffle-directory shuffle-dir-to-compare output-directory
    exit 1
fi
MAIN_DIR=$1
CMP_DIR=$2
OP_DIR=$3

cd $MAIN_DIR
if [ ! -d $OP_DIR ]; then
  echo Output dir does not exist: $OP_DIR
  exit 1
fi
for module in `ls *.classlist`; do
  echo $module
  if [ -f $CMP_DIR/$module ]; then
    cat $module $CMP_DIR/$module |sort | uniq -u > $OP_DIR/$module
  fi
done
